export const AXIOS_POKEMONS = 'AXIOS_POKEMONS';
export const AXIOS_SELECTEDPOKEMONSEARCH = 'AXIOS_SELECTEDPOKEMONSEARCH';
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON';
export const SET_SELECTED_POKEMON_SEARCH = 'SET_SELECTED_POKEMON_SEARCH';
export const SELECTED_POKEMONS_DATA_API = 'SELECTED_POKEMONS_DATA_API';
export const SET_POKEMON_MODAL_VISIBLE = 'SET_POKEMON_MODAL_VISIBLE';
export const HANDLE_MODAL = 'HANDLE_MODAL';


export const LOAD_POKEMON_MODAL = 'LOAD_POKEMON_MODAL';